"""Initial migration

Revision ID: 053c69acfc4c
Revises: 
Create Date: 2026-03-02 00:05:10.897395

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "053c69acfc4c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
