"""Create users table

Revision ID: 4b21b90f3f43
Revises: 053c69acfc4c
Create Date: 2026-03-02 00:25:34.519779

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b21b90f3f43"
down_revision: str | Sequence[str] | None = "053c69acfc4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("username", sa.String(length=255), nullable=False),
    sa.Column("password_hash", sa.LargeBinary(), nullable=False),
    sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_users"))
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
